builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - template/**
      - example-config.json
checksum:
  name_template: "checksums.txt"
changelog:
  skip: false
release:
  # draft: true
  prerelease: auto
  mode: replace
